### ISSUE TITLE
Add type hints across the repo

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#172]
Integrate type hints and checking w/ `mypy`.

**Comment by mhchia** [comment]
@NIC619 and I discussed a bit. We just started to work on the type hints since it will be extremely helpful for us when tracing the code. The current status is, we had `mypy` running in the linting test after https://github.com/libp2p/py-libp2p/pull/188 is merged, but got a bunch of [errors](https://travis-ci.com/libp2p/py-libp2p/jobs/219112868). We started from pubsub, and will finish type-hinting of all of the necessary components.

### TODOs
- [ ] host
- [ ] network
- [ ] peer
- [ ] protocol_muxer
- [ ] network
- [ ] pubsub
- [ ] routing
- [ ] security
- [ ] stream_muxer
- [ ] transport

**Comment by ChihChengLiang** [comment]
Fixed security in #200

**Comment by ChihChengLiang** [comment]
Fix stream_muxer and transport in #203, now moving to protocol_muxer

**Comment by mhchia** [comment]
Now that typing is added across the repo except for `kademlia`, IMO it makes sense to enable `mypy` and fix the errors in the next step.

**Comment by ChihChengLiang** [comment]
On it

**Comment by ChihChengLiang** [comment]
After #232, this task is done.
