### ISSUE TITLE
Remove py-libp2p-daemon

### ISSUE THREAD

**Issue by carver** [libp2p/py-libp2p#296]
pypi rejects releases with this kind of dependency:

https://github.com/libp2p/py-libp2p/blob/811cd7813a74ef55110e1ae09dac7028c6caa0a4/setup.py#L12-L13

I had to manually remove that line from the tagged commit before releasing.

Some options:
- remove it (maybe it's cruft that is not necessary anymore?)
- inline it (maybe it's small enough that it's worth just bringing into this repo)
- do a proper release of `py-libp2p-daemon`

**Comment by mhchia** [comment]
Sorry for the inconvenience. p2pclient is needed in the interop test. I'm leaning toward to keep it. However, p2pclient depends on pylibp2p directly as it's install_require. Would you mind doing a release with p2pclient removed from the tests dependency first, when doing the release? And then I will do a release for p2pclient, which depends on your pylibp2p release. Then,  we can add p2pclient back to the test dependency and do a second release for pylibp2p?

**Comment by ralexstokes** [comment]
just to chime in here, i think having `py-libp2p` be the "foundational" package here (possibly used by `p2pclient`) makes the most sense -- while the extent to which we make affordances to `libp2p` towards this end is subjective, i'd think its worthwhile exploring the interop tests to see if we can't accomplish them another way -- for example, a full interop suite would also involve `rust-libp2p`, `nim-libp2p` and `js-libp2p` alongside `go-libp2p` where we won't have client bindings (easily)

**Comment by mhchia** [comment]
@carver 

> Or maybe the p2pclient dependency can move into a tox dependency definition. But I think the ideal thing is to break the circular dependency somehow.

I agree that we should break the circular dependency. My motivation to let `p2pclient`(i.e. libp2p daemon) stay as `py-libp2p`'s tests dependency is because it is convenient to know if a change is interoperable with the other clients when we add new functionality or fix something, at least with go-libp2p which is the reference implementation. It is also helpful when we want to move fast and not deviate other implementations, with the interoperability test in our tests and CI.

In this sense, does it make sense if we let `p2pclient` stay in the tests(or extract to another directory) and move it into tox dependency for now, and remove it when the codebase becomes more stable?

@ralexstokes 

>  i'd think its worthwhile exploring the interop tests to see if we can't accomplish them another way -- for example, a full interop suite would also involve rust-libp2p, nim-libp2p and js-libp2p alongside go-libp2p where we won't have client bindings (easily)

It sounds a great idea, though it also sounds a huge work if we want to be interoperable with all of them. Did anyone bring this up in the interop lock-in event?

**Comment by carver** [comment]
> In this sense, does it make sense if we let `p2pclient` stay in the tests(or extract to another directory) and move it into tox dependency for now, and remove it when the codebase becomes more stable?

I think the best solution then might be to only install `p2pclient` in the specific tox environment that runs these integration tests, something like:

```
[testenv:py37-interop]
deps = p2pclient
```
