### ISSUE TITLE
Update protobuf version

### ISSUE THREAD

**Issue by ToJen** [libp2p/py-libp2p#470]
### Description

The current version of protobuf ([3.10.0](https://github.com/libp2p/py-libp2p/blob/main/setup.py#L61)) used in this project is now outdated. The [latest is 5.27.0](https://pypi.org/project/protobuf/).

### Motivation

Attempting to use both `web3==6.19.0` and `libp2p==0.1.5` results in this:

```bash
ERROR: Cannot install -r requirements.txt (line 12) and -r requirements.txt (line 6) because these package versions have conflicting dependencies.

The conflict is caused by:
    web3 6.19.0 depends on protobuf>=4.21.6
    libp2p 0.1.5 depends on protobuf<4.0.0 and >=3.10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

This prevents projects from being able to use py-libp2p and web3.py together.

### Current Implementation

Only supports an older version of protobuf.

### Are you planning to do it yourself in a pull request ?

No

**Comment by pacrob** [comment]
Thanks for the note, @ToJen. `main` is currently built with `protobuf==4.25.3`, but I haven't put a release out since there's been so much to clean up. It does look like I'll need to bump it to properly support `py312` anyway. Looking to get beta out in the next few weeks, so I'll make sure that's included.
